//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentFinderTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogFinderTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogFinderTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentFinderTests.LogFinderTestResources", typeof(LogFinderTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                   C:\Users\yogergitGet-GitActivity [datetime]::Today
        ///                  &gt;&gt; TerminatingError(Get-GitActivity): &quot;Cannot process argument transformation on parameter &apos;SinceDate&apos;. Cannot convert value &quot;[datetime]::Today&quot; to type &quot;System.DateTime&quot;. Error: &quot;Ciąg nie został rozpoznany jako prawidłowy element DateTime.&quot;&quot;
        ///                  Get-GitActivity : Cannot process argument transformation on parameter &apos;SinceDate&apos;. Cannot convert value &quot;[datetime]::Tod
        ///                  ay&quot; to type &quot;System.Da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowershellFirstLogEntry {
            get {
                return ResourceManager.GetString("PowershellFirstLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                   ***********************
        ///                  Windows PowerShell transcript start
        ///                  Start time: 20170121082655
        ///                  Username: DAS-PERSON\yoger
        ///                  RunAs User: DAS-PERSON\yoger
        ///                  Machine: DAS-PERSON (Microsoft Windows NT 10.0.14393.0)
        ///                  Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        ///                  Process ID: 6628
        ///                  PSVersion: 5.1.14393.693
        ///                  PSEdit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowershellLogContent {
            get {
                return ResourceManager.GetString("PowershellLogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                   C:\Users\yogergitGet-GitActivity ([datetime]::Today).
        /// </summary>
        internal static string PowershellSecondLogEntry {
            get {
                return ResourceManager.GetString("PowershellSecondLogEntry", resourceCulture);
            }
        }
    }
}
